# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.narodmon: debug

# https://www.home-assistant.io/integrations/debugpy/
# If you need to debug uncomment the line below
debugpy:

narodmon:
  devices:
    - name: "Narodmon"
      sensors:
        - type: pm
          id_regexp: "12345"
          display_name: "PM2.5"
        - type: pm
          id_regexp: "12346"
          display_name: "PM10"
        - type: temperature
        - type: humidity
        - type: pressure
        - type: radiation

        # - temperature
        #- humidity
        #- pm
      scan_interval:
        seconds: 61
